// Code generated by protoc-gen-go.
// source: stela.proto
// DO NOT EDIT!

/*
Package stela is a generated protocol buffer package.

It is generated from these files:
	stela.proto

It has these top-level messages:
	AddClientRequest
	ConnectRequest
	SubscribeRequest
	RegisterRequest
	DiscoverRequest
	DiscoverAllRequest
	AddClientResponse
	ServiceResponse
	SubscribeResponse
	RegisterResponse
	DiscoverResponse
*/
package stela

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request
type AddClientRequest struct {
	ClientAddress string `protobuf:"bytes,1,opt,name=client_address,json=clientAddress" json:"client_address,omitempty"`
}

func (m *AddClientRequest) Reset()                    { *m = AddClientRequest{} }
func (m *AddClientRequest) String() string            { return proto.CompactTextString(m) }
func (*AddClientRequest) ProtoMessage()               {}
func (*AddClientRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddClientRequest) GetClientAddress() string {
	if m != nil {
		return m.ClientAddress
	}
	return ""
}

type ConnectRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConnectRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type SubscribeRequest struct {
	ClientId    string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubscribeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SubscribeRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type RegisterRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Hostname string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Port     int32  `protobuf:"varint,5,opt,name=port" json:"port,omitempty"`
	Priority int32  `protobuf:"varint,6,opt,name=priority" json:"priority,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RegisterRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegisterRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type DiscoverRequest struct {
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *DiscoverRequest) Reset()                    { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string            { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()               {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DiscoverRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type DiscoverAllRequest struct {
}

func (m *DiscoverAllRequest) Reset()                    { *m = DiscoverAllRequest{} }
func (m *DiscoverAllRequest) String() string            { return proto.CompactTextString(m) }
func (*DiscoverAllRequest) ProtoMessage()               {}
func (*DiscoverAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Response
type AddClientResponse struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *AddClientResponse) Reset()                    { *m = AddClientResponse{} }
func (m *AddClientResponse) String() string            { return proto.CompactTextString(m) }
func (*AddClientResponse) ProtoMessage()               {}
func (*AddClientResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddClientResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type ServiceResponse struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Priority int32  `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
}

func (m *ServiceResponse) Reset()                    { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()               {}
func (*ServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServiceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ServiceResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceResponse) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type SubscribeResponse struct {
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DiscoverResponse struct {
	Services []*ServiceResponse `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *DiscoverResponse) Reset()                    { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string            { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()               {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DiscoverResponse) GetServices() []*ServiceResponse {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*AddClientRequest)(nil), "stela.AddClientRequest")
	proto.RegisterType((*ConnectRequest)(nil), "stela.ConnectRequest")
	proto.RegisterType((*SubscribeRequest)(nil), "stela.SubscribeRequest")
	proto.RegisterType((*RegisterRequest)(nil), "stela.RegisterRequest")
	proto.RegisterType((*DiscoverRequest)(nil), "stela.DiscoverRequest")
	proto.RegisterType((*DiscoverAllRequest)(nil), "stela.DiscoverAllRequest")
	proto.RegisterType((*AddClientResponse)(nil), "stela.AddClientResponse")
	proto.RegisterType((*ServiceResponse)(nil), "stela.ServiceResponse")
	proto.RegisterType((*SubscribeResponse)(nil), "stela.SubscribeResponse")
	proto.RegisterType((*RegisterResponse)(nil), "stela.RegisterResponse")
	proto.RegisterType((*DiscoverResponse)(nil), "stela.DiscoverResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stela service

type StelaClient interface {
	AddClient(ctx context.Context, in *AddClientRequest, opts ...grpc.CallOption) (Stela_AddClientClient, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Stela_ConnectClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	DiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	DiscoverAll(ctx context.Context, in *DiscoverAllRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// Peer related RPC is used to request all peer members
	PeerDiscover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	PeerDiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	PeerDiscoverAll(ctx context.Context, in *DiscoverAllRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
}

type stelaClient struct {
	cc *grpc.ClientConn
}

func NewStelaClient(cc *grpc.ClientConn) StelaClient {
	return &stelaClient{cc}
}

func (c *stelaClient) AddClient(ctx context.Context, in *AddClientRequest, opts ...grpc.CallOption) (Stela_AddClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Stela_serviceDesc.Streams[0], c.cc, "/stela.Stela/AddClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &stelaAddClientClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stela_AddClientClient interface {
	Recv() (*AddClientResponse, error)
	grpc.ClientStream
}

type stelaAddClientClient struct {
	grpc.ClientStream
}

func (x *stelaAddClientClient) Recv() (*AddClientResponse, error) {
	m := new(AddClientResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stelaClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Stela_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Stela_serviceDesc.Streams[1], c.cc, "/stela.Stela/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &stelaConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stela_ConnectClient interface {
	Recv() (*ServiceResponse, error)
	grpc.ClientStream
}

type stelaConnectClient struct {
	grpc.ClientStream
}

func (x *stelaConnectClient) Recv() (*ServiceResponse, error) {
	m := new(ServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stelaClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Discover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) DiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/DiscoverOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) DiscoverAll(ctx context.Context, in *DiscoverAllRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/DiscoverAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) PeerDiscover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/PeerDiscover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) PeerDiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/PeerDiscoverOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) PeerDiscoverAll(ctx context.Context, in *DiscoverAllRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/PeerDiscoverAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stela service

type StelaServer interface {
	AddClient(*AddClientRequest, Stela_AddClientServer) error
	Connect(*ConnectRequest, Stela_ConnectServer) error
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	DiscoverOne(context.Context, *DiscoverRequest) (*ServiceResponse, error)
	DiscoverAll(context.Context, *DiscoverAllRequest) (*DiscoverResponse, error)
	// Peer related RPC is used to request all peer members
	PeerDiscover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	PeerDiscoverOne(context.Context, *DiscoverRequest) (*ServiceResponse, error)
	PeerDiscoverAll(context.Context, *DiscoverAllRequest) (*DiscoverResponse, error)
}

func RegisterStelaServer(s *grpc.Server, srv StelaServer) {
	s.RegisterService(&_Stela_serviceDesc, srv)
}

func _Stela_AddClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddClientRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StelaServer).AddClient(m, &stelaAddClientServer{stream})
}

type Stela_AddClientServer interface {
	Send(*AddClientResponse) error
	grpc.ServerStream
}

type stelaAddClientServer struct {
	grpc.ServerStream
}

func (x *stelaAddClientServer) Send(m *AddClientResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Stela_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StelaServer).Connect(m, &stelaConnectServer{stream})
}

type Stela_ConnectServer interface {
	Send(*ServiceResponse) error
	grpc.ServerStream
}

type stelaConnectServer struct {
	grpc.ServerStream
}

func (x *stelaConnectServer) Send(m *ServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Stela_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_DiscoverOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).DiscoverOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/DiscoverOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).DiscoverOne(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_DiscoverAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).DiscoverAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/DiscoverAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).DiscoverAll(ctx, req.(*DiscoverAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_PeerDiscover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).PeerDiscover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/PeerDiscover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).PeerDiscover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_PeerDiscoverOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).PeerDiscoverOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/PeerDiscoverOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).PeerDiscoverOne(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_PeerDiscoverAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).PeerDiscoverAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/PeerDiscoverAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).PeerDiscoverAll(ctx, req.(*DiscoverAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stela_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stela.Stela",
	HandlerType: (*StelaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _Stela_Subscribe_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Stela_Register_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Stela_Discover_Handler,
		},
		{
			MethodName: "DiscoverOne",
			Handler:    _Stela_DiscoverOne_Handler,
		},
		{
			MethodName: "DiscoverAll",
			Handler:    _Stela_DiscoverAll_Handler,
		},
		{
			MethodName: "PeerDiscover",
			Handler:    _Stela_PeerDiscover_Handler,
		},
		{
			MethodName: "PeerDiscoverOne",
			Handler:    _Stela_PeerDiscoverOne_Handler,
		},
		{
			MethodName: "PeerDiscoverAll",
			Handler:    _Stela_PeerDiscoverAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddClient",
			Handler:       _Stela_AddClient_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Connect",
			Handler:       _Stela_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stela.proto",
}

func init() { proto.RegisterFile("stela.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x9b, 0xb5, 0xd9, 0xda, 0xd3, 0xb1, 0x76, 0x87, 0x3f, 0x0b, 0xe5, 0x66, 0x44, 0x42,
	0xea, 0x0d, 0xd3, 0x54, 0xb8, 0x41, 0x02, 0x41, 0x28, 0x02, 0x71, 0x03, 0x28, 0x7d, 0x80, 0xa9,
	0x4d, 0x8e, 0x20, 0x52, 0x16, 0x17, 0xdb, 0x9b, 0xc4, 0x33, 0xf0, 0x12, 0x5c, 0xf2, 0x98, 0x28,
	0x8e, 0xed, 0x64, 0x2e, 0x99, 0xaa, 0xee, 0x2e, 0xfe, 0xec, 0xef, 0xeb, 0x39, 0x3f, 0x1f, 0x17,
	0x86, 0x42, 0x52, 0xbe, 0x3c, 0x5b, 0x73, 0x26, 0x19, 0xfa, 0x6a, 0x11, 0xbe, 0x82, 0x71, 0x94,
	0xa6, 0xf3, 0x3c, 0xa3, 0x42, 0xc6, 0xf4, 0xf3, 0x8a, 0x84, 0xc4, 0x67, 0x70, 0x94, 0x28, 0xe1,
	0x62, 0x99, 0xa6, 0x9c, 0x84, 0x08, 0xbc, 0x53, 0x6f, 0x3a, 0x88, 0xef, 0x55, 0x6a, 0x54, 0x89,
	0xe1, 0x73, 0x38, 0x9a, 0xb3, 0xa2, 0xa0, 0xc4, 0x1a, 0x9f, 0xc0, 0x40, 0x1b, 0xb3, 0x54, 0x7b,
	0xfa, 0x95, 0xf0, 0x39, 0x0d, 0x63, 0x18, 0x2f, 0xae, 0x56, 0x22, 0xe1, 0xd9, 0x8a, 0xb6, 0x31,
	0xe0, 0x53, 0x38, 0x14, 0xc4, 0xaf, 0xb3, 0x84, 0x2e, 0x8a, 0xe5, 0x25, 0x05, 0x7b, 0x6a, 0x7f,
	0xa8, 0xb5, 0x2f, 0xcb, 0x4b, 0x0a, 0xff, 0x7a, 0x30, 0x8a, 0xe9, 0x7b, 0x26, 0x24, 0xf1, 0xad,
	0x32, 0x11, 0x7a, 0x8d, 0x2c, 0xf5, 0x8d, 0x13, 0xe8, 0xff, 0x60, 0x42, 0x2a, 0xbd, 0x5b, 0x9d,
	0x37, 0x6b, 0x0c, 0xe0, 0xc0, 0x30, 0xe8, 0xa9, 0x2d, 0xb3, 0x2c, 0x93, 0xd6, 0x8c, 0xcb, 0xc0,
	0x3f, 0xf5, 0xa6, 0x7e, 0xac, 0xbe, 0xcb, 0xa4, 0x35, 0xcf, 0x18, 0xcf, 0xe4, 0xaf, 0x60, 0x5f,
	0xe9, 0x76, 0x1d, 0xbe, 0x84, 0xd1, 0x87, 0x4c, 0x24, 0xec, 0xba, 0xae, 0x74, 0x8b, 0x06, 0x1f,
	0x00, 0x1a, 0x57, 0x94, 0xe7, 0xda, 0x18, 0x9e, 0xc3, 0x71, 0xe3, 0xd2, 0xc4, 0x9a, 0x15, 0x82,
	0x6e, 0x87, 0xff, 0xdb, 0x83, 0xd1, 0xa2, 0xca, 0xb5, 0x06, 0xc3, 0xc2, 0x6b, 0x61, 0xb1, 0xd7,
	0xce, 0xa2, 0xfb, 0x7f, 0x16, 0xbd, 0x16, 0x16, 0xbe, 0xc3, 0xe2, 0x3e, 0x1c, 0x37, 0x46, 0xa1,
	0x2a, 0x27, 0x44, 0x18, 0xd7, 0x57, 0xa9, 0xb5, 0x8f, 0x30, 0xae, 0xa1, 0xe9, 0xb2, 0x67, 0xd0,
	0xd7, 0x84, 0xca, 0xb9, 0xec, 0x4e, 0x87, 0xb3, 0x47, 0x67, 0xd5, 0x60, 0x3b, 0x0d, 0xc6, 0xf6,
	0xdc, 0xec, 0x8f, 0x0f, 0xfe, 0xa2, 0x3c, 0x83, 0xef, 0x61, 0x60, 0xd1, 0xe1, 0x89, 0x36, 0xba,
	0x2f, 0x60, 0x12, 0x6c, 0x6e, 0xe8, 0x8a, 0x3a, 0xe7, 0x1e, 0xbe, 0x86, 0x03, 0x3d, 0xf8, 0xf8,
	0x50, 0x1f, 0xbc, 0xf9, 0x10, 0x26, 0x2d, 0x15, 0x29, 0xf7, 0x3b, 0x18, 0xd8, 0xe6, 0x6d, 0x05,
	0xee, 0xcb, 0xb0, 0x15, 0x6c, 0x72, 0xea, 0xe0, 0x1b, 0xe8, 0x1b, 0x52, 0x68, 0x7e, 0xc9, 0x79,
	0x05, 0x93, 0x93, 0x0d, 0xbd, 0x69, 0x37, 0x50, 0xad, 0xdd, 0x19, 0x4d, 0x6b, 0x77, 0xe9, 0x87,
	0x1d, 0x7c, 0x0b, 0x43, 0xa3, 0x7e, 0x2d, 0xa8, 0x35, 0xa1, 0x15, 0x01, 0xce, 0xeb, 0x80, 0x28,
	0xcf, 0xf1, 0xb1, 0x13, 0x50, 0xcf, 0xf9, 0x6d, 0x55, 0x44, 0x70, 0xf8, 0x8d, 0x88, 0xdf, 0xa5,
	0x91, 0x39, 0x8c, 0x9a, 0x11, 0xbb, 0x35, 0xf3, 0xe9, 0x66, 0xc8, 0xce, 0x0d, 0xad, 0xf6, 0xd5,
	0xdf, 0xf2, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xf8, 0x79, 0x9d, 0xa5, 0x05, 0x00,
	0x00,
}
