// Code generated by protoc-gen-go.
// source: stela.proto
// DO NOT EDIT!

/*
Package stela is a generated protocol buffer package.

It is generated from these files:
	stela.proto

It has these top-level messages:
	SubscribeResponse
	RegisteResponse
	ServiceMessage
	SubscribeRequest
	DiscoverRequest
	DiscoverResponse
	ConnectRequest
*/
package stela

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubscribeResponse struct {
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegisteResponse struct {
}

func (m *RegisteResponse) Reset()                    { *m = RegisteResponse{} }
func (m *RegisteResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisteResponse) ProtoMessage()               {}
func (*RegisteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServiceMessage struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Priority int32  `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
}

func (m *ServiceMessage) Reset()                    { *m = ServiceMessage{} }
func (m *ServiceMessage) String() string            { return proto.CompactTextString(m) }
func (*ServiceMessage) ProtoMessage()               {}
func (*ServiceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceMessage) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ServiceMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceMessage) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceMessage) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type SubscribeRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubscribeRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type DiscoverRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *DiscoverRequest) Reset()                    { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string            { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()               {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DiscoverRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type DiscoverResponse struct {
	Services []*ServiceMessage `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *DiscoverResponse) Reset()                    { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string            { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()               {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DiscoverResponse) GetServices() []*ServiceMessage {
	if m != nil {
		return m.Services
	}
	return nil
}

type ConnectRequest struct {
	ClientUuid string `protobuf:"bytes,1,opt,name=client_uuid,json=clientUuid" json:"client_uuid,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ConnectRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeResponse)(nil), "stela.SubscribeResponse")
	proto.RegisterType((*RegisteResponse)(nil), "stela.RegisteResponse")
	proto.RegisterType((*ServiceMessage)(nil), "stela.ServiceMessage")
	proto.RegisterType((*SubscribeRequest)(nil), "stela.SubscribeRequest")
	proto.RegisterType((*DiscoverRequest)(nil), "stela.DiscoverRequest")
	proto.RegisterType((*DiscoverResponse)(nil), "stela.DiscoverResponse")
	proto.RegisterType((*ConnectRequest)(nil), "stela.ConnectRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stela service

type StelaClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Stela_ConnectClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Register(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*RegisteResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	DiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceMessage, error)
}

type stelaClient struct {
	cc *grpc.ClientConn
}

func NewStelaClient(cc *grpc.ClientConn) StelaClient {
	return &stelaClient{cc}
}

func (c *stelaClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Stela_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Stela_serviceDesc.Streams[0], c.cc, "/stela.Stela/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &stelaConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stela_ConnectClient interface {
	Recv() (*ServiceMessage, error)
	grpc.ClientStream
}

type stelaConnectClient struct {
	grpc.ClientStream
}

func (x *stelaConnectClient) Recv() (*ServiceMessage, error) {
	m := new(ServiceMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stelaClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) Register(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*RegisteResponse, error) {
	out := new(RegisteResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/stela.Stela/Discover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stelaClient) DiscoverOne(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServiceMessage, error) {
	out := new(ServiceMessage)
	err := grpc.Invoke(ctx, "/stela.Stela/DiscoverOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stela service

type StelaServer interface {
	Connect(*ConnectRequest, Stela_ConnectServer) error
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Register(context.Context, *ServiceMessage) (*RegisteResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	DiscoverOne(context.Context, *DiscoverRequest) (*ServiceMessage, error)
}

func RegisterStelaServer(s *grpc.Server, srv StelaServer) {
	s.RegisterService(&_Stela_serviceDesc, srv)
}

func _Stela_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StelaServer).Connect(m, &stelaConnectServer{stream})
}

type Stela_ConnectServer interface {
	Send(*ServiceMessage) error
	grpc.ServerStream
}

type stelaConnectServer struct {
	grpc.ServerStream
}

func (x *stelaConnectServer) Send(m *ServiceMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Stela_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Register(ctx, req.(*ServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stela_DiscoverOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StelaServer).DiscoverOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stela.Stela/DiscoverOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StelaServer).DiscoverOne(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stela_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stela.Stela",
	HandlerType: (*StelaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _Stela_Subscribe_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Stela_Register_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Stela_Discover_Handler,
		},
		{
			MethodName: "DiscoverOne",
			Handler:    _Stela_DiscoverOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Stela_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stela.proto",
}

func init() { proto.RegisterFile("stela.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0xc7, 0x09, 0x90, 0x25, 0x4c, 0x56, 0x7c, 0xcc, 0x6a, 0x97, 0x28, 0x97, 0x65, 0x73, 0xe2,
	0x84, 0x16, 0xda, 0x9e, 0x50, 0xab, 0x4a, 0x6d, 0x8f, 0x6d, 0xa5, 0xa0, 0x9e, 0x51, 0x48, 0x46,
	0xd4, 0x12, 0xc4, 0xa9, 0xed, 0x20, 0xf5, 0x15, 0xfa, 0x58, 0x7d, 0xb2, 0x0a, 0xe7, 0x83, 0xef,
	0x43, 0x6f, 0x9e, 0x9f, 0x67, 0xe6, 0x3f, 0xfe, 0x7b, 0xc0, 0x96, 0x8a, 0x96, 0xc1, 0x30, 0x11,
	0x5c, 0x71, 0x34, 0x75, 0xe0, 0xfd, 0x82, 0xee, 0x34, 0x9d, 0xcb, 0x50, 0xb0, 0x39, 0xf9, 0x24,
	0x13, 0x1e, 0x4b, 0xf2, 0xba, 0xd0, 0xf6, 0x69, 0xc1, 0xa4, 0xda, 0xa2, 0x0f, 0x03, 0x5a, 0x53,
	0x12, 0x6b, 0x16, 0xd2, 0x23, 0x49, 0x19, 0x2c, 0x08, 0x11, 0xea, 0x71, 0xb0, 0x22, 0xc7, 0xe8,
	0x1b, 0x83, 0xa6, 0xaf, 0xcf, 0xe8, 0x82, 0xf5, 0xca, 0xa5, 0xd2, 0xbc, 0xaa, 0x79, 0x19, 0xa3,
	0x03, 0x8d, 0x20, 0x8a, 0x04, 0x49, 0xe9, 0xd4, 0xf4, 0x55, 0x11, 0x6e, 0x3a, 0x25, 0x5c, 0x28,
	0xa7, 0xde, 0x37, 0x06, 0xa6, 0xaf, 0xcf, 0x9b, 0x4e, 0x89, 0x60, 0x5c, 0x30, 0xf5, 0xee, 0x98,
	0x9a, 0x97, 0xb1, 0x77, 0x05, 0x9d, 0x9d, 0xa1, 0xdf, 0x52, 0x92, 0x0a, 0xff, 0xc1, 0x4f, 0x99,
	0xcd, 0x37, 0xdb, 0x99, 0xca, 0xce, 0xd9, 0x53, 0xb0, 0x22, 0xef, 0x12, 0xda, 0xf7, 0x4c, 0x86,
	0x7c, 0x4d, 0xe2, 0x1b, 0x55, 0x0f, 0xd0, 0xd9, 0x56, 0x65, 0x6e, 0xe0, 0x08, 0xac, 0x3c, 0x45,
	0x3a, 0x46, 0xbf, 0x36, 0xb0, 0xc7, 0xbf, 0x87, 0x99, 0xb9, 0xfb, 0x1e, 0xf9, 0x65, 0x9a, 0x37,
	0x82, 0xd6, 0x1d, 0x8f, 0x63, 0x0a, 0x55, 0xa1, 0xfd, 0x17, 0xec, 0x70, 0xc9, 0x28, 0x56, 0xb3,
	0x34, 0x65, 0x51, 0x2e, 0x0d, 0x19, 0x7a, 0x49, 0x59, 0x34, 0xfe, 0xac, 0x82, 0x39, 0xdd, 0x74,
	0xc5, 0x09, 0x34, 0xf2, 0x62, 0x2c, 0x84, 0xf6, 0x9b, 0xb9, 0xa7, 0xf5, 0xbd, 0xca, 0x7f, 0x03,
	0x6f, 0xa1, 0x59, 0xba, 0x85, 0xbd, 0x22, 0xef, 0xc0, 0x3f, 0xd7, 0x39, 0xbe, 0xc8, 0xbf, 0xbe,
	0x82, 0x13, 0xb0, 0xf2, 0x7d, 0x10, 0x78, 0x5a, 0xc8, 0xfd, 0x93, 0xe3, 0xc3, 0xbd, 0xa9, 0xe0,
	0x35, 0x58, 0x85, 0x7f, 0x58, 0x64, 0x1d, 0x7c, 0x83, 0xdb, 0x3b, 0xe2, 0x65, 0xf9, 0x0d, 0xd8,
	0x05, 0x7d, 0x8e, 0xe9, 0x6c, 0x87, 0x73, 0xef, 0x9f, 0xff, 0xd0, 0xeb, 0x7e, 0xf1, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x89, 0xb1, 0x33, 0xdf, 0xfd, 0x02, 0x00, 0x00,
}
